name: git_url_parse
description: A low level git url parser.
version: 0.0.1
homepage: https://gitjournal.io

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.6.0

dev_dependencies:
  test: ^1.12.0
  build_runner:
  freezed: ^0.6.1
